export const CREATE_MEMORY_REQUEST = "CREATE_MEMORY_REQUEST";
export const CREATE_MEMORY_SUCCESS = "CREATE_MEMORY_SUCCESS";
export const CREATE_MEMORY_FAILED = "CREATE_MEMORY_FAILED";

export const FETCH_MEMORY_REQUEST = "FETCH_MEMORY_REQUEST";
export const FETCH_MEMORY_SUCCESS = "FETCH_MEMORY_SUCCESS ";
export const FETCH_MEMORY_FAILED = "FETCH_MEMORY_FAILED";

export const UPDATE_MEMORY_REQUEST = "UPDATE_MEMORY_REQUEST";
export const UPDATE_MEMORY_SUCCESS = "UPDATE_MEMORY_SUCCESS";
export const UPDATE_MEMORY_FAILED = "UPDATE_MEMORY_FAILED";

export const LIKE_AND_DISLIKE_MEMORY_REQUEST = "LIKE_AND_DISLIKE_MEMORY_REQUEST";
export const LIKE_AND_DISLIKE_MEMORY_SUCCESS = "LIKE_AND_DISLIKE_MEMORY_SUCCESS";
export const LIKE_AND_DISLIKE_MEMORY_FAILED = "LIKE_AND_DISLIKE_MEMORY_FAILED";

export const DELETE_MEMORY_REQUEST = "DELETE_MEMORY_REQUEST";
export const DELETE_MEMORY_SUCCESS = "DELETE_MEMORY_SUCCESS";
export const DELETE_MEMORY_FAILED = "DELETE_MEMORY_FAILED";